#Основная надпись
class TitleBlock_typeDef():
    def __init__(self):
        self.tb01a_DocumentName = ''
        self.tb01b_DocumentType = ''
        self.tb02_DocumentDesignator = ''
        self.tb04_Letter_left = ''
        self.tb04_Letter_middle = ''
        self.tb04_Letter_right = ''
        self.tb07_SheetIndex = ''
        self.tb08_SheetsTotal = ''
        self.tb09_Organization = ''
        self.tb10d_ActivityType_Extra = ''
        self.tb11a_Name_Designer = ''
        self.tb11b_Name_Checker = ''
        self.tb11c_Name_TechnicalSupervisor = ''
        self.tb11d_Name_Extra = ''
        self.tb11e_Name_NormativeSupervisor = ''
        self.tb11f_Name_Approver = ''
        self.tb13a_SignatureDate_Designer = ''
        self.tb13b_SignatureDate_Checker = ''
        self.tb13c_SignatureDate_TechnicalSupervisor = ''
        self.tb13d_SignatureDate_Extra = ''
        self.tb13e_SignatureDate_NormativeSupervisor = ''
        self.tb13f_SignatureDate_Approver = ''
        self.tb19_OriginalInventoryNumber = ''
        self.tb21_ReplacedOriginalInventoryNumber = ''
        self.tb22_DuplicateInventoryNumber = ''
        self.tb24_BaseDocumentDesignator = ''
        self.tb25_FirstReferenceDocumentDesignator = ''